"""initial tables

Revision ID: 1753d05f6977
Revises: 
Create Date: 2026-07-26 02:28:54.932537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1753d05f6977'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coin',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('logo_url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coin_name'), 'coin', ['name'], unique=True)
    op.create_index(op.f('ix_coin_symbol'), 'coin', ['symbol'], unique=True)
    op.create_table('news_articles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('sentiment', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('holding',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('coin_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('avg_buy_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coin_id'], ['coin.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news_coin_tag',
    sa.Column('news_id', sa.UUID(), nullable=False),
    sa.Column('coin_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['coin_id'], ['coin.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['news_id'], ['news_articles.id'], ),
    sa.PrimaryKeyConstraint('news_id', 'coin_id')
    )
    op.create_table('price_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('coin_id', sa.UUID(), nullable=False),
    sa.Column('interval', sa.String(), nullable=False),
    sa.Column('open', sa.Numeric(), nullable=False),
    sa.Column('close', sa.Numeric(), nullable=False),
    sa.Column('high', sa.Numeric(), nullable=False),
    sa.Column('low', sa.Numeric(), nullable=False),
    sa.Column('volume', sa.Numeric(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['coin_id'], ['coin.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'ts')
    )
    op.create_index(op.f('ix_price_history_ts'), 'price_history', ['ts'], unique=False)
    op.create_table('transaction',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('coin_id', sa.UUID(), nullable=False),
    sa.Column('tx_type', sa.String(), nullable=False),
    sa.Column('quantity', sa.Numeric(), nullable=False),
    sa.Column('price_at_trade', sa.Numeric(), nullable=False),
    sa.Column('total_value', sa.Numeric(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coin_id'], ['coin.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallet',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('balance_usd', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watchlist',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('coin_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['coin_id'], ['coin.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute(
        "SELECT create_hypertable('price_history', 'ts', if_not_exists => TRUE);"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlist')
    op.drop_table('wallet')
    op.drop_table('transaction')
    op.drop_index(op.f('ix_price_history_ts'), table_name='price_history')
    op.drop_table('price_history')
    op.drop_table('news_coin_tag')
    op.drop_table('holding')
    op.drop_table('user')
    op.drop_table('news_articles')
    op.drop_index(op.f('ix_coin_symbol'), table_name='coin')
    op.drop_index(op.f('ix_coin_name'), table_name='coin')
    op.drop_table('coin')
    # ### end Alembic commands ###
